# The container name used for the run container
container-name-run : "cogk8s-django-run"
# The container name used for the tools container
container-name-tools : "cogk8s-django-tools"

# The project root on the host for the run container to mount to container-path-run
host-path-run : "."
# The project root on the host for the tools container to mount to container-path-tools
host-path-tools : "."

# The project root in the run container to mount to host-path-run
container-path-run : "/app"
# The project root in the tools container that will be mounted to host-path-tools
container-path-tools : "/app"

# The port mappings between the host and the container in the form [host:container]
container-port-map : "3000:3000"
# The port mappings between the host and the container for the debug port in the form [host:container]
container-port-map-debug : "5858:5858"


# The name for the dockerfile for the run container
dockerfile-run : "Dockerfile"
# The name for the dockerfile for the tools container
dockerfile-tools : "Dockerfile-tools"

# The name of image to create from dockerfile-run
image-name-run : "cogk8s-django-run"
# The name of image to create from dockerfile-tools
image-name-tools : "cogk8s-django-tools"

# The command to build the code and docker image for RUN
build-cmd-run : "python -m compileall ."
# The command to execute tests for the code in the tools container
test-cmd : "python manage.py test"
# The command to build the code and docker image for DEBUG
build-cmd-debug : "python -m compileall ."

# The command to run the code in the run container
run-cmd : ""
# The command to execute debug of the code in the tools container
debug-cmd : "python manage.py runserver --noreload"
# The command to stop the code
stop-cmd : ""

# The relative path to the helm chart used for Kubernetes deployment
chart-path : "chart/cogk8s"

# The IBM version of this configuration
version : "0.0.3"
ibm-generated-id : "e45ff536-1668-4f7a-a776-ce2f3b54d57e"
ibm-cloud-app-id : "2298893b-fa2d-4dcd-972f-6c2b1dd93a75"
credentials-filepath : "localdev-config.json, server/localdev-config.json"